### ISSUE TITLE
[BUG] Cannot use the function `glogger.RequestGorillaMuxMiddlewareLogger`

### ISSUE THREAD

**Issue by malta895** [mia-platform/glogger#32]
## Describe the bug
After the update from v2 to v3, with the changes introduced in #28, I am no longer able to instantiate a middleware logger by using the function `logger.RequestGorillaMuxMiddlewareLogger`. It appears that the function has been placed in the `middleware` submodule, which is not reachable by code outside of the library.

## How To Reproduce

1.  Update glogger from v2 to v3
2. Rename the function `RequestMiddlewareLogger` to `RequestGorillaMuxMiddlewareLogger`, as stated in the CHANGELOG
3. This leads to a compilation error.

## Expected behavior

By renaming such function everything should work as before in v2

## System Info

- Go Version go1.19.5

**Comment by malta895** [comment]
@fredmaggiowski You are right, I tried again to import it and now it works.

However the readme does not mention the `middleware` module, the example still uses the `glogger` module.  Also in the changelog it is not mentioned that the function has been moved to that module, it only says that it has been renamed.

If you agree, I can open a PR to fix the readme and the changelog 😃

**Comment by fredmaggiowski** [comment]
Yeah feel free to open a PR to fix them, thank you!
